In [89]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

import os
print(os.listdir("../input"))
import warnings
warnings.filterwarnings('ignore')


['IMDB Dataset.csv']


In [3]:

df=pd.read_csv('../input/IMDB Dataset.csv')
df.head(10)

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive
5,"Probably my all-time favorite movie, a story o...",positive
6,I sure would like to see a resurrection of a u...,positive
7,"This show was an amazing, fresh & innovative i...",negative
8,Encouraged by the positive comments about this...,negative
9,If you like original gut wrenching laughter yo...,positive


In [6]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
review       50000 non-null object
sentiment    50000 non-null object
dtypes: object(2)
memory usage: 781.3+ KB


In [11]:
X=df['review']
y=df['sentiment']

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
vectorizer=CountVectorizer()
X_train_vect=vectorizer.fit_transform(X_train)
X_test_vect=vectorizer.transform(X_test)

In [71]:
model=LogisticRegression()
model.fit(X_train_vect,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [72]:
y_predict=model.predict(X_test_vect)

In [73]:
print(confusion_matrix(y_test,y_predict))
#TN 4362 #FP 599
#FN 521 TP 4518

[[4362  599]
 [ 521 4518]]


In [74]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

    negative       0.89      0.88      0.89      4961
    positive       0.88      0.90      0.89      5039

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000



In [88]:
print("1st test mostly positive")
test1 = ["""I really loved this movie. The acting was fantastic and the story was engaging from start to finish. 
The cinematography and music were beautiful and made many scenes very memorable. 
The characters were interesting and easy to connect with. 
Overall it was a great film and I would definitely recommend it to anyone looking for an enjoyable movie experience."""]

test1_vect=vectorizer.transform(test1)
print(model.predict(test1_vect))
print(print(model.classes_),model.predict_proba(test1_vect))

print("2nd test mostly negative")
test2=["""This movie was very disappointing. The story was boring and predictable 
and the acting was weak. Many scenes felt slow and unnecessary, and the dialogue was poorly written. 
I struggled to finish the movie and honestly felt like it was a waste of time."""]
test2_vect=vectorizer.transform(test2)
print(model.predict(test2_vect))
print(model.predict_proba(test2_vect))

print("3rd test mixed")

test3 = ["""The movie had a good idea and some scenes were enjoyable, and the soundtrack was nice. 
However, the pacing was slow and parts of the story felt weak and predictable. 
Some characters were interesting while others were poorly developed. 
Overall it was an okay movie with both good and bad moments."""]

test3_vect = vectorizer.transform(test3)

print(model.predict(test3_vect))
print(model.predict_proba(test3_vect))

1st test mostly positive
['positive']
['negative' 'positive']
None [[0.00863069 0.99136931]]
2nd test mostly negative
['negative']
[[9.99974245e-01 2.57552798e-05]]
3rd test mixed
['negative']
[[0.96976928 0.03023072]]
